"""Initial migration

Revision ID: 576f0f9bb2c1
Revises: b8ce15df7294
Create Date: 2024-12-23 09:30:30.121254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576f0f9bb2c1'
down_revision: Union[str, None] = 'b8ce15df7294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
